//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QPService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/order_svc/Service1", ConfigurationName="QPService.OrderDeliveryServiceSoap")]
    public interface OrderDeliveryServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/order_svc/Service1/consumeDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<QPService.ConsumeDeliveryResponse> ConsumeDeliveryAsync(QPService.ConsumeDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/order_svc/Service1/CancelOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<QPService.CancelServiceResultModel> CancelOrderAsync(string OrderNo, string Type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/order_svc/Service1/UpdateOrderInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<QPService.UpdateOrderInfoModel> UpdateOrderInfoAsync(string OrderNo, int StoreId, string DeliveryDate, int DeliveryTimeGroup, string DeliveryTimeRange, bool ClearCollectionHistory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/order_svc/Service1/UpdateDeliveredOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<QPService.UpdateDeliveredOrderResponse> UpdateDeliveredOrderAsync(QPService.UpdateDeliveredOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/order_svc/Service1/OrderStateInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<QPService.OrderStateInfoServiceModel> OrderStateInfoAsync(string orderNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/order_svc/Service1/ProductReturn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<QPService.ProductReturnResponse> ProductReturnAsync(QPService.ProductReturnRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class DeliveryRequest
    {
        
        private DeliveryAction deliveryActionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DeliveryAction DeliveryAction
        {
            get
            {
                return this.deliveryActionField;
            }
            set
            {
                this.deliveryActionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class DeliveryAction
    {
        
        private long orderIdField;
        
        private string consignmentField;
        
        private long masterOrderIdField;
        
        private bool orderPriorityField;
        
        private long parentOrderIdField;
        
        private string orderDateField;
        
        private string orderTimeField;
        
        private string userCodeField;
        
        private string userPwdField;
        
        private bool updateDeliveryActionField;
        
        private bool successCrmCallField;
        
        private string crmMessageField;
        
        private int maxCapturePercentageField;
        
        private string shippingServiceNameField;
        
        private string customerNoteField;
        
        private DeliveryModel deliveryModelField;
        
        private Customer customerField;
        
        private Addres fromAddressField;
        
        private Addres toAddressField;
        
        private string claimDateField;
        
        private string deliveryDateField;
        
        private string deliveryTimeField;
        
        private int deliveryTimeGroupField;
        
        private decimal servicePriceYTLField;
        
        private decimal minDeliveryTotalPriceYTLField;
        
        private string serivePricePayerField;
        
        private string payerCompanyCodeField;
        
        private Item[] itemsField;
        
        private decimal discountTotalYTLField;
        
        private decimal discountSubtotalTLField;
        
        private CustomerInvoice customerInvoiceField;
        
        private Payment[] paymentsField;
        
        private string kurbanTypeCodeField;
        
        private string kurbanDeliveryPlaceCodeField;
        
        private string baseStoreIdField;
        
        private SaleChannelObj saleChannelField;
        
        private string lastPickupTimeField;
        
        private bool collectOrderField;
        
        private string subStoreIdField;
        
        private decimal idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long OrderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Consignment
        {
            get
            {
                return this.consignmentField;
            }
            set
            {
                this.consignmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long MasterOrderId
        {
            get
            {
                return this.masterOrderIdField;
            }
            set
            {
                this.masterOrderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool OrderPriority
        {
            get
            {
                return this.orderPriorityField;
            }
            set
            {
                this.orderPriorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long ParentOrderId
        {
            get
            {
                return this.parentOrderIdField;
            }
            set
            {
                this.parentOrderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OrderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string OrderTime
        {
            get
            {
                return this.orderTimeField;
            }
            set
            {
                this.orderTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserCode
        {
            get
            {
                return this.userCodeField;
            }
            set
            {
                this.userCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string UserPwd
        {
            get
            {
                return this.userPwdField;
            }
            set
            {
                this.userPwdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool UpdateDeliveryAction
        {
            get
            {
                return this.updateDeliveryActionField;
            }
            set
            {
                this.updateDeliveryActionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool SuccessCrmCall
        {
            get
            {
                return this.successCrmCallField;
            }
            set
            {
                this.successCrmCallField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CrmMessage
        {
            get
            {
                return this.crmMessageField;
            }
            set
            {
                this.crmMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int MaxCapturePercentage
        {
            get
            {
                return this.maxCapturePercentageField;
            }
            set
            {
                this.maxCapturePercentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ShippingServiceName
        {
            get
            {
                return this.shippingServiceNameField;
            }
            set
            {
                this.shippingServiceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CustomerNote
        {
            get
            {
                return this.customerNoteField;
            }
            set
            {
                this.customerNoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public DeliveryModel DeliveryModel
        {
            get
            {
                return this.deliveryModelField;
            }
            set
            {
                this.deliveryModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public Customer Customer
        {
            get
            {
                return this.customerField;
            }
            set
            {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public Addres FromAddress
        {
            get
            {
                return this.fromAddressField;
            }
            set
            {
                this.fromAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public Addres ToAddress
        {
            get
            {
                return this.toAddressField;
            }
            set
            {
                this.toAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ClaimDate
        {
            get
            {
                return this.claimDateField;
            }
            set
            {
                this.claimDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string DeliveryDate
        {
            get
            {
                return this.deliveryDateField;
            }
            set
            {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string DeliveryTime
        {
            get
            {
                return this.deliveryTimeField;
            }
            set
            {
                this.deliveryTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int DeliveryTimeGroup
        {
            get
            {
                return this.deliveryTimeGroupField;
            }
            set
            {
                this.deliveryTimeGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public decimal ServicePriceYTL
        {
            get
            {
                return this.servicePriceYTLField;
            }
            set
            {
                this.servicePriceYTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public decimal MinDeliveryTotalPriceYTL
        {
            get
            {
                return this.minDeliveryTotalPriceYTLField;
            }
            set
            {
                this.minDeliveryTotalPriceYTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string SerivePricePayer
        {
            get
            {
                return this.serivePricePayerField;
            }
            set
            {
                this.serivePricePayerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string PayerCompanyCode
        {
            get
            {
                return this.payerCompanyCodeField;
            }
            set
            {
                this.payerCompanyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=27)]
        public Item[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public decimal DiscountTotalYTL
        {
            get
            {
                return this.discountTotalYTLField;
            }
            set
            {
                this.discountTotalYTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public decimal DiscountSubtotalTL
        {
            get
            {
                return this.discountSubtotalTLField;
            }
            set
            {
                this.discountSubtotalTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public CustomerInvoice CustomerInvoice
        {
            get
            {
                return this.customerInvoiceField;
            }
            set
            {
                this.customerInvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=31)]
        public Payment[] Payments
        {
            get
            {
                return this.paymentsField;
            }
            set
            {
                this.paymentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string KurbanTypeCode
        {
            get
            {
                return this.kurbanTypeCodeField;
            }
            set
            {
                this.kurbanTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string KurbanDeliveryPlaceCode
        {
            get
            {
                return this.kurbanDeliveryPlaceCodeField;
            }
            set
            {
                this.kurbanDeliveryPlaceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string BaseStoreId
        {
            get
            {
                return this.baseStoreIdField;
            }
            set
            {
                this.baseStoreIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public SaleChannelObj SaleChannel
        {
            get
            {
                return this.saleChannelField;
            }
            set
            {
                this.saleChannelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string LastPickupTime
        {
            get
            {
                return this.lastPickupTimeField;
            }
            set
            {
                this.lastPickupTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public bool CollectOrder
        {
            get
            {
                return this.collectOrderField;
            }
            set
            {
                this.collectOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string SubStoreId
        {
            get
            {
                return this.subStoreIdField;
            }
            set
            {
                this.subStoreIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class DeliveryModel
    {
        
        private int deliveryModelIdField;
        
        private string deliveryModelNameField;
        
        private string deliveryTypeField;
        
        private string marketplaceDeliveryModelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DeliveryModelId
        {
            get
            {
                return this.deliveryModelIdField;
            }
            set
            {
                this.deliveryModelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DeliveryModelName
        {
            get
            {
                return this.deliveryModelNameField;
            }
            set
            {
                this.deliveryModelNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DeliveryType
        {
            get
            {
                return this.deliveryTypeField;
            }
            set
            {
                this.deliveryTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MarketplaceDeliveryModel
        {
            get
            {
                return this.marketplaceDeliveryModelField;
            }
            set
            {
                this.marketplaceDeliveryModelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/order_svc/Service1")]
    public partial class ProductReturnResponseModel
    {
        
        private int orderIdField;
        
        private bool successField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OrderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class ProductReturnReasonRequestModel
    {
        
        private string idField;
        
        private string nameField;
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class ProductReturnItemRequestModel
    {
        
        private string productIdField;
        
        private string productNameField;
        
        private decimal quantityField;
        
        private string noteField;
        
        private string customerNoteField;
        
        private string[] imagesField;
        
        private ProductReturnReasonRequestModel customerReasonField;
        
        private ProductReturnReasonRequestModel saleChannelReasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProductName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CustomerNote
        {
            get
            {
                return this.customerNoteField;
            }
            set
            {
                this.customerNoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] Images
        {
            get
            {
                return this.imagesField;
            }
            set
            {
                this.imagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public ProductReturnReasonRequestModel CustomerReason
        {
            get
            {
                return this.customerReasonField;
            }
            set
            {
                this.customerReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ProductReturnReasonRequestModel SaleChannelReason
        {
            get
            {
                return this.saleChannelReasonField;
            }
            set
            {
                this.saleChannelReasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class ProductReturnRequestModel
    {
        
        private int orderIdField;
        
        private string returnIdField;
        
        private System.DateTime returnDateField;
        
        private ProductReturnItemRequestModel[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OrderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ReturnId
        {
            get
            {
                return this.returnIdField;
            }
            set
            {
                this.returnIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ReturnDate
        {
            get
            {
                return this.returnDateField;
            }
            set
            {
                this.returnDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public ProductReturnItemRequestModel[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/order_svc/Service1")]
    public partial class OrderStateInfoServiceModel
    {
        
        private decimal orderIdField;
        
        private int orderStateIdField;
        
        private string orderStateNameField;
        
        private string vehicleNoField;
        
        private System.Nullable<double> latitudeField;
        
        private System.Nullable<double> longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal OrderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int OrderStateId
        {
            get
            {
                return this.orderStateIdField;
            }
            set
            {
                this.orderStateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrderStateName
        {
            get
            {
                return this.orderStateNameField;
            }
            set
            {
                this.orderStateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string VehicleNo
        {
            get
            {
                return this.vehicleNoField;
            }
            set
            {
                this.vehicleNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<double> Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<double> Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/order_svc/Service1")]
    public partial class UpdateDeliveryAmountResponse
    {
        
        private bool operationResultField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool OperationResult
        {
            get
            {
                return this.operationResultField;
            }
            set
            {
                this.operationResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class ProductItem
    {
        
        private string shopDefinedCodeField;
        
        private decimal priceYTLField;
        
        private float amountField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ShopDefinedCode
        {
            get
            {
                return this.shopDefinedCodeField;
            }
            set
            {
                this.shopDefinedCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal PriceYTL
        {
            get
            {
                return this.priceYTLField;
            }
            set
            {
                this.priceYTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class DeliveredOrder
    {
        
        private long orderIdField;
        
        private string deliveredDateField;
        
        private string deliveredTimeField;
        
        private ProductItem[] itemsField;
        
        private Payment[] paymentsField;
        
        private decimal discountTotalYTLField;
        
        private decimal idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long OrderId
        {
            get
            {
                return this.orderIdField;
            }
            set
            {
                this.orderIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DeliveredDate
        {
            get
            {
                return this.deliveredDateField;
            }
            set
            {
                this.deliveredDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DeliveredTime
        {
            get
            {
                return this.deliveredTimeField;
            }
            set
            {
                this.deliveredTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public ProductItem[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Payment[] Payments
        {
            get
            {
                return this.paymentsField;
            }
            set
            {
                this.paymentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal DiscountTotalYTL
        {
            get
            {
                return this.discountTotalYTLField;
            }
            set
            {
                this.discountTotalYTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class Payment
    {
        
        private bool onTheDoorPaymentField;
        
        private PaymentMethod paymentMethodField;
        
        private PaymentOption paymentOptionField;
        
        private decimal amountYTLField;
        
        private decimal captureAmountYTLField;
        
        private int installmentCountField;
        
        private System.Nullable<decimal> pointsUsedYTLField;
        
        private string bankProvisionNoField;
        
        private string creditCardNoField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool OnTheDoorPayment
        {
            get
            {
                return this.onTheDoorPaymentField;
            }
            set
            {
                this.onTheDoorPaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PaymentMethod PaymentMethod
        {
            get
            {
                return this.paymentMethodField;
            }
            set
            {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PaymentOption PaymentOption
        {
            get
            {
                return this.paymentOptionField;
            }
            set
            {
                this.paymentOptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal AmountYTL
        {
            get
            {
                return this.amountYTLField;
            }
            set
            {
                this.amountYTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal CaptureAmountYTL
        {
            get
            {
                return this.captureAmountYTLField;
            }
            set
            {
                this.captureAmountYTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int InstallmentCount
        {
            get
            {
                return this.installmentCountField;
            }
            set
            {
                this.installmentCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> PointsUsedYTL
        {
            get
            {
                return this.pointsUsedYTLField;
            }
            set
            {
                this.pointsUsedYTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string BankProvisionNo
        {
            get
            {
                return this.bankProvisionNoField;
            }
            set
            {
                this.bankProvisionNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CreditCardNo
        {
            get
            {
                return this.creditCardNoField;
            }
            set
            {
                this.creditCardNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class PaymentMethod
    {
        
        private int idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class PaymentOption
    {
        
        private int idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class UpdateDeliveredAmount
    {
        
        private DeliveredOrder deliveredOrderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DeliveredOrder DeliveredOrder
        {
            get
            {
                return this.deliveredOrderField;
            }
            set
            {
                this.deliveredOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/order_svc/Service1")]
    public partial class UpdateOrderInfoModel
    {
        
        private bool statusField;
        
        private string infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/order_svc/Service1")]
    public partial class CancelServiceResultModel
    {
        
        private bool responseField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class SaleChannelObj
    {
        
        private int channelIdField;
        
        private string channelNameField;
        
        private string channelOrderIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ChannelId
        {
            get
            {
                return this.channelIdField;
            }
            set
            {
                this.channelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ChannelName
        {
            get
            {
                return this.channelNameField;
            }
            set
            {
                this.channelNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ChannelOrderId
        {
            get
            {
                return this.channelOrderIdField;
            }
            set
            {
                this.channelOrderIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class CustomerInvoice
    {
        
        private bool prepareInvoiceField;
        
        private decimal productTotalYTLField;
        
        private decimal servicePriceYTLField;
        
        private decimal vadeFarkYTLField;
        
        private decimal invoiceTotalYTLField;
        
        private string nameField;
        
        private string addressField;
        
        private DistrictObj districtField;
        
        private CityObj cityField;
        
        private string taxNoField;
        
        private string taxOfficeField;
        
        private string tel1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool PrepareInvoice
        {
            get
            {
                return this.prepareInvoiceField;
            }
            set
            {
                this.prepareInvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal ProductTotalYTL
        {
            get
            {
                return this.productTotalYTLField;
            }
            set
            {
                this.productTotalYTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal ServicePriceYTL
        {
            get
            {
                return this.servicePriceYTLField;
            }
            set
            {
                this.servicePriceYTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal VadeFarkYTL
        {
            get
            {
                return this.vadeFarkYTLField;
            }
            set
            {
                this.vadeFarkYTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal InvoiceTotalYTL
        {
            get
            {
                return this.invoiceTotalYTLField;
            }
            set
            {
                this.invoiceTotalYTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public DistrictObj District
        {
            get
            {
                return this.districtField;
            }
            set
            {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public CityObj City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TaxNo
        {
            get
            {
                return this.taxNoField;
            }
            set
            {
                this.taxNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TaxOffice
        {
            get
            {
                return this.taxOfficeField;
            }
            set
            {
                this.taxOfficeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Tel1
        {
            get
            {
                return this.tel1Field;
            }
            set
            {
                this.tel1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class DistrictObj
    {
        
        private long idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class CityObj
    {
        
        private long idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class Item
    {
        
        private int shopIdField;
        
        private string shopAccTypeField;
        
        private string shopNameField;
        
        private int storeIdField;
        
        private string storeNameField;
        
        private string shopDefinedStoreCodeField;
        
        private long productModelIdField;
        
        private string productModelNameField;
        
        private long productIdField;
        
        private string productNameField;
        
        private string shopDefinedCodeField;
        
        private bool packableField;
        
        private decimal priceYTLField;
        
        private byte vATField;
        
        private int dM3Field;
        
        private float amountField;
        
        private float giftAmountField;
        
        private string unitField;
        
        private string noteField;
        
        private string systemNoteField;
        
        private string giftNoteField;
        
        private string alternativeProductRequestedField;
        
        private string alternativeProductNoteField;
        
        private string kosulKoduField;
        
        private int reyonOrderField;
        
        private System.Nullable<decimal> discountTLField;
        
        private System.Nullable<decimal> receiptDiscountTLField;
        
        private System.Nullable<decimal> minAmountField;
        
        private System.Nullable<decimal> maxAmountField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ShopId
        {
            get
            {
                return this.shopIdField;
            }
            set
            {
                this.shopIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ShopAccType
        {
            get
            {
                return this.shopAccTypeField;
            }
            set
            {
                this.shopAccTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ShopName
        {
            get
            {
                return this.shopNameField;
            }
            set
            {
                this.shopNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int StoreId
        {
            get
            {
                return this.storeIdField;
            }
            set
            {
                this.storeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StoreName
        {
            get
            {
                return this.storeNameField;
            }
            set
            {
                this.storeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ShopDefinedStoreCode
        {
            get
            {
                return this.shopDefinedStoreCodeField;
            }
            set
            {
                this.shopDefinedStoreCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long ProductModelId
        {
            get
            {
                return this.productModelIdField;
            }
            set
            {
                this.productModelIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ProductModelName
        {
            get
            {
                return this.productModelNameField;
            }
            set
            {
                this.productModelNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ProductName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ShopDefinedCode
        {
            get
            {
                return this.shopDefinedCodeField;
            }
            set
            {
                this.shopDefinedCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool Packable
        {
            get
            {
                return this.packableField;
            }
            set
            {
                this.packableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal PriceYTL
        {
            get
            {
                return this.priceYTLField;
            }
            set
            {
                this.priceYTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public byte VAT
        {
            get
            {
                return this.vATField;
            }
            set
            {
                this.vATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int DM3
        {
            get
            {
                return this.dM3Field;
            }
            set
            {
                this.dM3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public float Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public float GiftAmount
        {
            get
            {
                return this.giftAmountField;
            }
            set
            {
                this.giftAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string SystemNote
        {
            get
            {
                return this.systemNoteField;
            }
            set
            {
                this.systemNoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string GiftNote
        {
            get
            {
                return this.giftNoteField;
            }
            set
            {
                this.giftNoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string AlternativeProductRequested
        {
            get
            {
                return this.alternativeProductRequestedField;
            }
            set
            {
                this.alternativeProductRequestedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string AlternativeProductNote
        {
            get
            {
                return this.alternativeProductNoteField;
            }
            set
            {
                this.alternativeProductNoteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string KosulKodu
        {
            get
            {
                return this.kosulKoduField;
            }
            set
            {
                this.kosulKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int ReyonOrder
        {
            get
            {
                return this.reyonOrderField;
            }
            set
            {
                this.reyonOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<decimal> DiscountTL
        {
            get
            {
                return this.discountTLField;
            }
            set
            {
                this.discountTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public System.Nullable<decimal> ReceiptDiscountTL
        {
            get
            {
                return this.receiptDiscountTLField;
            }
            set
            {
                this.receiptDiscountTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<decimal> MinAmount
        {
            get
            {
                return this.minAmountField;
            }
            set
            {
                this.minAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<decimal> MaxAmount
        {
            get
            {
                return this.maxAmountField;
            }
            set
            {
                this.maxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class Addres
    {
        
        private string nameField;
        
        private string addressField;
        
        private string zipField;
        
        private DistrictObj districtField;
        
        private CityObj cityField;
        
        private string tel1Field;
        
        private string tel2Field;
        
        private string tel3Field;
        
        private string taxNoField;
        
        private string taxOfficeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DistrictObj District
        {
            get
            {
                return this.districtField;
            }
            set
            {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public CityObj City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Tel1
        {
            get
            {
                return this.tel1Field;
            }
            set
            {
                this.tel1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Tel2
        {
            get
            {
                return this.tel2Field;
            }
            set
            {
                this.tel2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Tel3
        {
            get
            {
                return this.tel3Field;
            }
            set
            {
                this.tel3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TaxNo
        {
            get
            {
                return this.taxNoField;
            }
            set
            {
                this.taxNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TaxOffice
        {
            get
            {
                return this.taxOfficeField;
            }
            set
            {
                this.taxOfficeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="stringbased.service.shipment")]
    public partial class Customer
    {
        
        private string customerIdField;
        
        private int customerTypeField;
        
        private string clubCardNoField;
        
        private bool vIPField;
        
        private string nameField;
        
        private string addressField;
        
        private string zipField;
        
        private DistrictObj districtField;
        
        private CityObj cityField;
        
        private string tel1Field;
        
        private string tel2Field;
        
        private string tel3Field;
        
        private string emailField;
        
        private string taxNoField;
        
        private string taxOfficeField;
        
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int CustomerType
        {
            get
            {
                return this.customerTypeField;
            }
            set
            {
                this.customerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ClubCardNo
        {
            get
            {
                return this.clubCardNoField;
            }
            set
            {
                this.clubCardNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool VIP
        {
            get
            {
                return this.vIPField;
            }
            set
            {
                this.vIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public DistrictObj District
        {
            get
            {
                return this.districtField;
            }
            set
            {
                this.districtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public CityObj City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Tel1
        {
            get
            {
                return this.tel1Field;
            }
            set
            {
                this.tel1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Tel2
        {
            get
            {
                return this.tel2Field;
            }
            set
            {
                this.tel2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Tel3
        {
            get
            {
                return this.tel3Field;
            }
            set
            {
                this.tel3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TaxNo
        {
            get
            {
                return this.taxNoField;
            }
            set
            {
                this.taxNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string TaxOffice
        {
            get
            {
                return this.taxOfficeField;
            }
            set
            {
                this.taxOfficeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsumeDelivery", WrapperNamespace="http://tempuri.org/order_svc/Service1", IsWrapped=true)]
    public partial class ConsumeDeliveryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="stringbased.service.shipment", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="stringbased.service.shipment", IsNullable=true)]
        public QPService.DeliveryRequest DeliveryRequest;
        
        public ConsumeDeliveryRequest()
        {
        }
        
        public ConsumeDeliveryRequest(QPService.DeliveryRequest DeliveryRequest)
        {
            this.DeliveryRequest = DeliveryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsumeDeliveryResponse", WrapperNamespace="http://tempuri.org/order_svc/Service1", IsWrapped=true)]
    public partial class ConsumeDeliveryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/order_svc/Service1", Order=0)]
        public string ConsumeDeliveryResult;
        
        public ConsumeDeliveryResponse()
        {
        }
        
        public ConsumeDeliveryResponse(string ConsumeDeliveryResult)
        {
            this.ConsumeDeliveryResult = ConsumeDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDeliveredOrder", WrapperNamespace="http://tempuri.org/order_svc/Service1", IsWrapped=true)]
    public partial class UpdateDeliveredOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="stringbased.service.shipment", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="stringbased.service.shipment", IsNullable=true)]
        public QPService.UpdateDeliveredAmount UpdateDeliveredAmount;
        
        public UpdateDeliveredOrderRequest()
        {
        }
        
        public UpdateDeliveredOrderRequest(QPService.UpdateDeliveredAmount UpdateDeliveredAmount)
        {
            this.UpdateDeliveredAmount = UpdateDeliveredAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateDeliveredOrderResponse", WrapperNamespace="http://tempuri.org/order_svc/Service1", IsWrapped=true)]
    public partial class UpdateDeliveredOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/order_svc/Service1", Order=0)]
        public QPService.UpdateDeliveryAmountResponse UpdateDeliveredOrderResult;
        
        public UpdateDeliveredOrderResponse()
        {
        }
        
        public UpdateDeliveredOrderResponse(QPService.UpdateDeliveryAmountResponse UpdateDeliveredOrderResult)
        {
            this.UpdateDeliveredOrderResult = UpdateDeliveredOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProductReturn", WrapperNamespace="http://tempuri.org/order_svc/Service1", IsWrapped=true)]
    public partial class ProductReturnRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="stringbased.service.shipment", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="stringbased.service.shipment", IsNullable=true)]
        public QPService.ProductReturnRequestModel ProductReturn;
        
        public ProductReturnRequest()
        {
        }
        
        public ProductReturnRequest(QPService.ProductReturnRequestModel ProductReturn)
        {
            this.ProductReturn = ProductReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProductReturnResponse", WrapperNamespace="http://tempuri.org/order_svc/Service1", IsWrapped=true)]
    public partial class ProductReturnResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/order_svc/Service1", Order=0)]
        public QPService.ProductReturnResponseModel ProductReturnResult;
        
        public ProductReturnResponse()
        {
        }
        
        public ProductReturnResponse(QPService.ProductReturnResponseModel ProductReturnResult)
        {
            this.ProductReturnResult = ProductReturnResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface OrderDeliveryServiceSoapChannel : QPService.OrderDeliveryServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class OrderDeliveryServiceSoapClient : System.ServiceModel.ClientBase<QPService.OrderDeliveryServiceSoap>, QPService.OrderDeliveryServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OrderDeliveryServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(OrderDeliveryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), OrderDeliveryServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderDeliveryServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OrderDeliveryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderDeliveryServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OrderDeliveryServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OrderDeliveryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QPService.ConsumeDeliveryResponse> QPService.OrderDeliveryServiceSoap.ConsumeDeliveryAsync(QPService.ConsumeDeliveryRequest request)
        {
            return base.Channel.ConsumeDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<QPService.ConsumeDeliveryResponse> ConsumeDeliveryAsync(QPService.DeliveryRequest DeliveryRequest)
        {
            QPService.ConsumeDeliveryRequest inValue = new QPService.ConsumeDeliveryRequest();
            inValue.DeliveryRequest = DeliveryRequest;
            return ((QPService.OrderDeliveryServiceSoap)(this)).ConsumeDeliveryAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<QPService.CancelServiceResultModel> CancelOrderAsync(string OrderNo, string Type)
        {
            return base.Channel.CancelOrderAsync(OrderNo, Type);
        }
        
        public System.Threading.Tasks.Task<QPService.UpdateOrderInfoModel> UpdateOrderInfoAsync(string OrderNo, int StoreId, string DeliveryDate, int DeliveryTimeGroup, string DeliveryTimeRange, bool ClearCollectionHistory)
        {
            return base.Channel.UpdateOrderInfoAsync(OrderNo, StoreId, DeliveryDate, DeliveryTimeGroup, DeliveryTimeRange, ClearCollectionHistory);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QPService.UpdateDeliveredOrderResponse> QPService.OrderDeliveryServiceSoap.UpdateDeliveredOrderAsync(QPService.UpdateDeliveredOrderRequest request)
        {
            return base.Channel.UpdateDeliveredOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<QPService.UpdateDeliveredOrderResponse> UpdateDeliveredOrderAsync(QPService.UpdateDeliveredAmount UpdateDeliveredAmount)
        {
            QPService.UpdateDeliveredOrderRequest inValue = new QPService.UpdateDeliveredOrderRequest();
            inValue.UpdateDeliveredAmount = UpdateDeliveredAmount;
            return ((QPService.OrderDeliveryServiceSoap)(this)).UpdateDeliveredOrderAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<QPService.OrderStateInfoServiceModel> OrderStateInfoAsync(string orderNo)
        {
            return base.Channel.OrderStateInfoAsync(orderNo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QPService.ProductReturnResponse> QPService.OrderDeliveryServiceSoap.ProductReturnAsync(QPService.ProductReturnRequest request)
        {
            return base.Channel.ProductReturnAsync(request);
        }
        
        public System.Threading.Tasks.Task<QPService.ProductReturnResponse> ProductReturnAsync(QPService.ProductReturnRequestModel ProductReturn)
        {
            QPService.ProductReturnRequest inValue = new QPService.ProductReturnRequest();
            inValue.ProductReturn = ProductReturn;
            return ((QPService.OrderDeliveryServiceSoap)(this)).ProductReturnAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OrderDeliveryServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.OrderDeliveryServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OrderDeliveryServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.141.5:9091/Service/OrderDeliveryService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.OrderDeliveryServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.141.5:9091/Service/OrderDeliveryService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            OrderDeliveryServiceSoap,
            
            OrderDeliveryServiceSoap12,
        }
    }
}
